### ISSUE TITLE
Cannot use with Distillery > 2.1.0 

### ISSUE THREAD

**Issue by ndac-todoroki** [alertlogic/mix_erllambda#7]
## What
The recent Distillery releases had brought a breaking change where `Mix.Release` was renamed to `Distillery.Release`.
e.g. https://hexdocs.pm/distillery/changelog.html#210-unreleased

The new `Mix.Release` does not have sub module like `Mix.Releases.Assembler`. Please consider replacing that to `Distillery`, or use the new `Mix.Releases` for `elixir ~> 1.9.0`.

thanks

**Comment by ndac-todoroki** [comment]
(Maybe it is `distillery`'s fault where it introduced a minor version change with a breaking change)

**Comment by motobob** [comment]
@ndac-todoroki thanks you for the note. will take a look next when after holidays
